# Generated by Django 4.2.11 on 2024-05-31 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChocolateTable',
            fields=[
                ('chocolate_id', models.AutoField(primary_key=True, serialize=False)),
                ('chocolate_name', models.CharField(max_length=100)),
                ('chocolate_price', models.IntegerField()),
                ('chocolate_description', models.CharField(max_length=100)),
                ('chocolate_quantity', models.IntegerField()),
                ('chocolate_variety', models.CharField(max_length=100)),
                ('chocolate_weight', models.IntegerField()),
                ('chocolate_event', models.CharField(max_length=100)),
                ('chocolate_shape', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CartTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('chocolate_id', models.ForeignKey(db_column='chocolate_id', on_delete=django.db.models.deletion.CASCADE, to='chocolate.chocolatetable')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
