# Generated by Django 4.2.11 on 2024-05-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chocolate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chocolatetable',
            old_name='chocolate_variety',
            new_name='chocolate_flavour',
        ),
    ]
